Update CI

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -6,18 +6,41 @@ on:
     branches: [master]
 
 jobs:
-  test:
+  nbdev-sync:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Test Library Sync
+        uses: fastai/workflows/nbdev-ci@master
+        with:
+          version: "3.8"
+          skip_test: true
+  
+  nbdev-test:
+    needs: nbdev-sync
     strategy:
       fail-fast: true
       matrix:
-        os:  [ubuntu]
-        version: ['3.8'] # ["3.7", "3.8", "3.9", "3.10", "3.11"]
-    runs-on: ${{ matrix.os }}-latest
+        py: ['3.8', '3.9', '3.10', '3.11']
+    runs-on: ubuntu-latest
     steps:
-      - uses: fastai/workflows/nbdev-ci@master
+      - name: Checkout Code
+        uses: actions/checkout@v3
+
+      - name: Set up Python
+        uses: actions/setup-python@v4
         with:
-          version: ${{ matrix.version }}
-          pre: 1
+          python-version: ${{ matrix.py }}
+          cache: "pip"
+          cache-dependency-path: settings.ini
+
+      - name: Install Library
+        run: |
+          pip install --upgrade pip
+          pip install -e .[dev]
+
+      - name: Run Tests
+        run: nbdev_test
+
       - name: test docs build
         if: ${{ (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') && matrix.version == '3.8' && matrix.os == 'ubuntu' }}
         run: |
@@ -33,3 +56,33 @@ jobs:
             ls -la _docs
             exit 1
           fi
+
+
+    # strategy:
+    #   fail-fast: true
+    #   matrix:
+    #     os:  [ubuntu]
+    #     version: ["3.8", "3.9", "3.10", "3.11"]
+    # runs-on: ${{ matrix.os }}-latest
+    # steps:
+    #   - uses: fastai/workflows/nbdev-ci@master
+    #     with:
+    #       version: "3.8"
+    #       # version: ${{ matrix.version }}
+    #       skip_test: true
+      
+    #   - name: test docs build
+    #     if: ${{ (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') && matrix.version == '3.8' && matrix.os == 'ubuntu' }}
+    #     run: |
+    #       set -ux
+    #       wget -q $(curl https://latest.fast.ai/pre/quarto-dev/quarto-cli/linux-amd64.deb)
+    #       sudo dpkg -i quarto*.deb
+    #       nbdev_docs
+    #       if [ -f "_docs/index.html" ]; then
+    #         echo "docs built successfully."
+    #       else
+    #         echo "index page not found in rendered docs."
+    #         ls -la
+    #         ls -la _docs
+    #         exit 1
+    #       fi
